'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SenecaDashboard

    Partial Public Class AccessTable
        Public Property ID As Integer
        Public Property SESA As String
        Public Property Role As String
        Public Property Initials As String
    
    End Class

End Namespace
