'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SenecaDashboard

    Partial Public Class InternalGroup
        Public Property ID As Integer
        Public Property AccNbr As String
        Public Property Cust As String
        Public Property InternalGroup1 As String
    
    End Class

End Namespace
