'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SenecaDashboard

    Partial Public Class LoginStamp
        Public Property ID As Integer
        Public Property SESA As String
        Public Property LoginDate As Nullable(Of Date)
    
    End Class

End Namespace
