'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OSQueue
    Public Property ID As Integer
    Public Property Q2CLISLSS As String
    Public Property Product As String
    Public Property Category As String
    Public Property ODRPath As String
    Public Property LineCode As String
    Public Property Processed As Nullable(Of Boolean)
    Public Property QueueGeneratedBy As String
    Public Property dateQueueGenerated As Nullable(Of Date)
    Public Property OS_SESA As String
    Public Property dateProcessed As Nullable(Of Date)
    Public Property CORev As String
    Public Property ProgressPoint As String
    Public Property OS_Comment As String
    Public Property Bays As Nullable(Of Integer)
    Public Property Tags As String
    Public Property PONumber As String
    Public Property CPQQuoteNumber As String
    Public Property ActionStat As String
    Public Property PM As String
    Public Property OrigProm As String
    Public Property CurrProm As String
    Public Property CommitedTo As String
    Public Property Designations As String
    Public Property AccountNo As String
    Public Property InternalGroup As Nullable(Of Boolean)
    Public Property CatalogueNumber As String
    Public Property PROJECT_MGR_LOC As String
    Public Property Price As String

End Class
