'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductCode
    Public Property ID As Integer
    Public Property LineCode As String
    Public Property Category As String
    Public Property ProductLine As String
    Public Property LineDescription As String
    Public Property ProductGroup As String
    Public Property MPG As String
    Public Property DAS As String
    Public Property DasDescription As String

End Class
